name: forecast_academy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - statsforecast>=1.7.0
      - mlforecast>=0.10.0
      - neuralforecast>=1.5.0
      - utilsforecast>=0.0.12
      - pandas>=2.0.0
      - numpy>=1.24.0
      - matplotlib>=3.7.0
      - plotly>=5.20.0
      - notebook
